// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Null(arg1) {
  return window['go']['server']['Api']['Null'](arg1);
}
