// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Print(arg1:string):Promise<void>;

export function RunCmd(arg1:string):Promise<string>;
