// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Print(arg1) {
  return window['go']['main']['App']['Print'](arg1);
}

export function RunCmd(arg1) {
  return window['go']['main']['App']['RunCmd'](arg1);
}
